env:
  es6: true
  browser: true
  commonjs: true

parserOptions:
  sourceType: module
  ecmaFeatures: 
    jsx: true
    experimentalObjectRestSpread: true

extends: ['htmlacademy/es6', 'plugin:react/recommended']

rules:
  react/prop-types: off